mikaelbr/node-notifier

notifiers/balloon.js

If Notifu ends with error code `4` it means, that the balloon has been closed with the `x` mark or it faded out, after moving mouse/pressing a key.

Added one more end state (error code) for balloon notifier.

---

lib/utils.js

This will allow a sort of unified syntax.

Allow terminal-notifier syntax to work with notify-send

---

bin.js
package.json

As suggested in #40, this commit adds a `bin` keyword in the `package.json` and a `bin.js` file that takes a title and message from the command line and launches a notification.
Additional configuration is not currently supported but can be easily added through more command line parameters.
Hope this helps.

Adds a simple command-line interface

---

notifiers/notifysend.js

I ran into strange behaviors when using the gulp plugin 'gulp-notify' with JSHint (or basically from a stream of several inputs) on my Ubuntu machine.
Only the last error message was showing up, all the other notifications was the defaults one ('Node Notification' // 'undefined').
By using 'which' plugin that checks if 'notify-send' exists in a synchronous way, it solved the issue. I'm not really sure why though...

Use 'which' in 'notifiy-send' notifier synchronously. Prevents strange options deletion

---

bin.js

Redirecting stdout of a tool to the notification is a really
useful workflow to receive errors: `my-tool | xargs -0 notify -m`
However, because `xargs -r` is not cross-platform,
the result is a constant stream of empty notifications.

CLI: do not show an empty message

---

bin.js

Without this, titles and messages become `true` if given on a command line with no argument.

Bin: set string options

---

lib/checkGrowl.js
notifiers/balloon.js
notifiers/growl.js

`checkGrowl` will fail if trying to run against a remote growl server by setting growl host.
Using the example from the docs:
```js
var Growl = require('node-notifier').Growl;
var GROWL_HOST = '10.0.2.2';
var notifier = new Growl({
name: 'Growl Name Used', // Defaults as 'Node'
host: GROWL_HOST,
port: 23053
});
notifier.notify({
title: 'Foo',
message: 'Hello World',
wait: false, // if wait for user interaction
// and other growl options like sticky etc.
sticky: false,
label: void 0,
priority: void 0
}, function (err, res) {
console.log(err, res);
});
```
This gives an error that growl can't be connected to. `checkGrowl` is trying to connect to 'localhost', which fails.

Add support for remote growl server

---

README.md

fix on KDE
not found: notify-send
You need to install `libnotify-bin`
sudo apt-get install libnotify-bin

add requirement to `libnotify-bin`

---

lib/utils.js
notifiers/balloon.js
notifiers/growl.js
notifiers/notificationcenter.js
notifiers/toaster.js

Sanitize response on `notify` callback
- Lowercase all response data
- Trim whitespace
- Return `activate` instead of `Activate` or `Activated`
Covers https://github.com/mikaelbr/node-notifier/issues/101
This is a breaking change.
Here is another upstream change from `toaster` that isn't necessary but will make life easier for consuming the API safely if someone forgets to sanitize: https://github.com/mikaelbr/toaster/pull/2

Sanitize response on `notify` callback

---

lib/utils.js
test/notify-send.js
test/utils.js

https://github.com/mikaelbr/node-notifier/issues/114 fixed
https://github.com/mikaelbr/node-notifier/issues/113 fixed

fix issues 113 & 114

---

lib/utils.js
test/toaster.js

https://github.com/mikaelbr/node-notifier/issues/99

---

lib/utils.js
test/balloon.js

Add support for passing 'type' option when using 'WindowsBalloon' (throught notifu).
Also handle sanitation of the give option for fallback
Add tests to check functionality

Add support for passing type option to WindowsBalloon (notifu)

---

lib/utils.js
notifiers/notifysend.js
test/index.js

Should fix #132 
I am not super good with tests and I'm kind of new to Open Source, so please feel free to let me know if there's anything wrong with test or the code I have added. The changes are very few so it should not be that difficult to review.

Checks 2nd parameter of the notify() method to be a function

---

lib/utils.js

A bug I encountered was that if I would pass `appID` option for windows toast, it would be removed and not set as an option for Snoar Toast.  
For it to work I had to use `appName` option then it worked perfectly fine.  
I could've created PR for [README](https://github.com/mikaelbr/node-notifier/blob/master/README.md#all-notification-options-with-their-defaults) to change the API description. 
However, code change will be more consistent for the API that `node-notifier` is using.

appID option not being set when passed to Snoar Toast (WIN10)

---

CONTRIBUTE.md
lib/utils.js

When someone uses [visionmedia/debug](https://github.com/visionmedia/debug) for logging he has to set `process.env.DEBUG` for enabling his own log messages.
He always sees the following output, because `node-notifier` only checks for the presence of the env var (`if (process.env.DEBUG)`):
```
node-notifier debug info (fileCommandJson):
[notifier path] [...]/node_modules/node-notifier/vendor/terminal-notifier.app/Contents/MacOS/terminal-notifier
[notifier options] -title "xyz" -message "🎉 some message here" -json "true"
```
Instead of checking for the presence you could check for the package name inside of the env var. Then someone could enable debug logging for `node-notifier` with setting the env var to something like this:
````
process.env.DEBUG = 'some-other,notifier';
````

Use a more specific condition for debug output.

---

lib/utils.js
test/notify-send.js

The `time` property specified in the documentation had
no effect since it wasn't link to notify-send
expire-time flag

fix: link notifier time property to notify-send expire-time flag

---

index.js
lib/utils.js
notifiers/toaster.js
package-lock.json
package.json

This uses the very simple [`is-wsl`](https://github.com/sindresorhus/is-wsl) package to check when node is being run under WSL (Windows Subsystem for Linux) and instead of using Linux's `NotifySend` notifier (which doesn't work) uses `WindowsToaster`.
Without this change, notifications inside WSL don't popup on Windows.

Enables the use of WindowsToaster when using WSL

---

README.md
lib/utils.js
package-lock.json
test/terminal-notifier.js

We ran into a jest issue (https://github.com/facebook/jest/issues/7890) where the new default timeout causes jest to think that the notification isn't finished after 1 second (which it isn't). I couldn't find a way in the current options (as pointed out in 270) to get the old "fire and forget" behavior. 
Related to #218, fix for #270. Allows for `timeout: false` to overwrite the default timeout set to allow for "fire and forgotten" notifications again.
I added a test for this, and all the tests were passing again. Let me know if you have any issues or comments and I can address them :)

Allow timeout: false to remove a timeout

---

README.md
lib/utils.js
test/terminal-notifier.js

Reverts mikaelbr/node-notifier#271
Reverts in master branch, creating new branch `v6` with these changes. Easier to maintain patch fixes on the master and have breaking changes in the v6 branch

Revert "Allow timeout: false to remove a timeout"

---

notifiers/balloon.js
notifiers/growl.js
notifiers/notificationcenter.js
notifiers/notifysend.js
notifiers/toaster.js
package-lock.json

Automagically bind `notify` methods on all wrapper classes so the notify method can be destructured within the import statement and not run into any `this` related errors.

Automagically Bind `notify` Methods

---

lib/utils.js
notifiers/notifysend.js

Hello, notify-send has an option to set the app name, but I couldn't be able to pass that option through node-notifier, so I made the additions that enables people to use that option if they want to, using node-notifier.
Although it seems notify-send man page doesn't say anything about this option, it's definitively there, I tested the option under some Ubuntu based systems and notify-send recognizes the option, also you can find information about the option from other sources like this one [notify-send options](http://vaskovsky.net/notify-send/linux.html).
One thing this option does is let you change the "notify-send" default app name, that shows in the notification no matter what in some notifications system.
For example, executing `notifier.notify({title: 'Hello Message', message: …

NotifySend support for app name

---

notifiers/toaster.js

Deep require of uuid versions is deprecated with v7 and should be replaced with the corresponding import. More details at https://github.com/uuidjs/uuid#deep-requires-now-deprecated

Use new uuidjs import convention

---

lib/utils.js
notifiers/toaster.js

Fix named pipe server hang when notifications are disabled in Windows 10.
This PR can't address root cause (due to snoretoast's behavior) but at least resolves the hanging issue. I think it's important to fix with some kind of change at least temporarily to prevent a permanent hang in certain use cases. (More info in #334.)
Fixes #334.

Fix hang on Disabled Windows 10 Notifications

---

notifiers/toaster.js

Deep requires of uuid have been deprecated, so I updated the import to get rid of DeprecationWarning.

Corrected the way of importing uuid

---

.prettierrc
CHANGELOG.md
README.md
lib/utils.js
test/notify-send.js
test/utils.js

Timeout/wait implementation seems to be lacking for Linux systems as of now. This PR tries to amend this. See https://github.com/facebook/jest/issues/9701 for context. 
Breaking change:
- Changes the notify-send API to match macOS and Windows with seconds for timeout. Also sets timeout to default to 10 seconds.

feat: implements proper timeout/wait behaviour for notify-send

---

notifiers/toaster.js

This fixes the named pipe creation when running in WSL.
Otherwise it would create the files in the project root like this:
```
.pipenotifierPipe-6d2386eb-7b1b-46dd-a8ac-cab4eee63c6d
```

Fix named pipe in WSL

---

notifiers/toaster.js

The mapper-function for the resultantData did not map "activate" to "click", so fixed the mapper to handle this. 
This introduces a breaking change.

fix: fixes mapping on snoretoast activate event, fixes #291

---

README.md

The metadata parameter was missing from the "Cross-Platform Advanced Usage" example in README.md

Add metadata parameter to example in README

---

vendor/mac.noindex/terminal-notifier.app/Contents/Info.plist

Based on the [comments of the author](https://github.com/julienXX/terminal-notifier/issues/275#issuecomment-561371857) of terminal-notifier, this flag was initially set to true to allow using icons with http link, however, given the security issues raised by code-analysers, it is a good practice to disable usage of http.

fix: Issue #294 NSAllowsArbitraryLoads flag set to false 

---

README.md

Most users use `electron-builder` to build electron apps, not using asar directly.
I append detail explanation for who use `electron-builder`. This works same like previous command, and is `electron-builder`'s recommended method(https://www.electron.build/configuration/configuration#overridable-per-platform-options).

detail explanation for electron packaging issues (electron-builder)

---

notifiers/toaster.js
test/toaster.js

Fix #377
This PR #373 caused customPath set in WindowsToaster constructor to be ignored.
* Fix use of customPath passed to constructor
* Added 2 unit tests

Fix issue #377: Fix customPath option in WindowsToaster constructor

---

.husky/pre-commit
package-lock.json
package.json

Upgrade husky@8 and lint-staged@13
New husky:
- Zero dependencies and lightweight (6 kB)
- Powered by modern new Git feature (core.hooksPath)
- Follows [npm](https://docs.npmjs.com/cli/v8/using-npm/scripts#best-practices) and [Yarn](https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall) best practices regarding autoinstall

chore: upgrade husky@8 and lint-staged@13
